Update terraform-infra.yml

diff --git a/pipelines/terraform-infra.yml b/pipelines/terraform-infra.yml
--- a/pipelines/terraform-infra.yml
+++ b/pipelines/terraform-infra.yml
@@ -24,27 +24,49 @@ stages:
     jobs:
       - job: Plan
         steps: 
+        
+        - task: AzureCLI@2
+          displayName: az login
+          inputs:
+            azureSubscription: ${{ variables.serviceConnection }}
+            scriptType: bash
+            scriptLocation: inlineScript
+            addSpnToEnvironment: true
+            inlineScript: |
+              set -eu  # fail on error
+              subscriptionId=$(az account show --query id -o tsv)
+              echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
+              echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;issecret=true]$servicePrincipalKey"
+              echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$subscriptionId"
+              echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
+        
          - task: TerraformInstaller@0
            displayName: Terraform - install v${{ variables.terraformVersion }}
            inputs:
              terraformVersion: ${{ variables.terraformVersion }}
 
-         - task: AzureCLI@2
+         - task: Bash@3
            displayName: Terraform init
            inputs:
-            azureSubscription: ${{ variables.serviceConnection }}
-            scriptType: bash
-            scriptLocation: inlineScript
             workingDirectory: ${{ variables.terraformDir }}
-            inlineScript: |
+            targetType: 'inline'
+            script: |
               terraform init -input=false
+            env:
+              ARM_SUBSCRIPTION_ID:  $(ARM_SUBSCRIPTION_ID)
+              ARM_CLIENT_ID:        $(ARM_CLIENT_ID)
+              ARM_CLIENT_SECRET:    $(ARM_CLIENT_SECRET)
+              ARM_TENANT_ID:        $(ARM_TENANT_ID)
               
-         - task: AzureCLI@2
+         - task: Bash@3
            displayName: Terraform plan
            inputs:
-            azureSubscription: ${{ variables.serviceConnection }}
-            scriptType: bash
-            scriptLocation: inlineScript
             workingDirectory: ${{ variables.terraformDir }}
-            inlineScript: |
+            targetType: 'inline'
+            script: |
               terraform plan -out "${{ variables.outFile }}"
+            env:
+              ARM_SUBSCRIPTION_ID:  $(ARM_SUBSCRIPTION_ID)
+              ARM_CLIENT_ID:        $(ARM_CLIENT_ID)
+              ARM_CLIENT_SECRET:    $(ARM_CLIENT_SECRET)
+              ARM_TENANT_ID:        $(ARM_TENANT_ID)
