Update terraform-infra.yml

diff --git a/pipelines/terraform-infra.yml b/pipelines/terraform-infra.yml
--- a/pipelines/terraform-infra.yml
+++ b/pipelines/terraform-infra.yml
@@ -25,20 +25,20 @@ stages:
       - job: Plan
         steps: 
         
-          - task: AzureCLI@2
-            displayName: az login
-            inputs:
-              azureSubscription: ${{ variables.serviceConnection }}
-              scriptType: bash
-              scriptLocation: inlineScript
-              addSpnToEnvironment: true
-              inlineScript: |
-                set -eu  # fail on error
-                subscriptionId=$(az account show --query id -o tsv)
-                echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
-                echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;issecret=true]$servicePrincipalKey"
-                echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$subscriptionId"
-                echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
+           - task: AzureCLI@2
+             displayName: az login
+             inputs:
+               azureSubscription: ${{ variables.serviceConnection }}
+               scriptType: bash
+               scriptLocation: inlineScript
+               addSpnToEnvironment: true
+               inlineScript: |
+                 set -eu  # fail on error
+                 subscriptionId=$(az account show --query id -o tsv)
+                 echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
+                 echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;issecret=true]$servicePrincipalKey"
+                 echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$subscriptionId"
+                 echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
         
            - task: TerraformInstaller@0
              displayName: Terraform - install v${{ variables.terraformVersion }}
